image: docker:stable
variables:
  IMAGE_NAME: ${CI_REGISTRY}/${CI_PROJECT_PATH}

stages:  
  - prebuild      
  - build
  # - push
  # - deploy

Prebuild:
  stage: prebuild 
  script:
  - set 

Construction:      
  stage: build
  script:
    #- docker compose build
    - docker image build -t ${IMAGE_NAME}:version .
  # tags:
  # - runner-builder

# Push:
#   stage: push
#   script:
#     - docker compose push

# Deploiement:
#   stage: deploy
#   script:
#     - echo "Un jour, on déploie l'application"