stages:        
  - build
  - push
  - deploy
Prebuild:
  stage: prebuild 
  script:
  - set 

Construction:      
  stage: build
  script:
    #- docker compose build
    - docker image build -t image:version .
  tags:
  - runner-builder

# Push:
#   stage: push
#   script:
#     - docker compose push

# Deploiement:
#   stage: deploy
#   script:
#     - echo "Un jour, on déploie l'application"