name: Deployement sitedocs
on: push
jobs:
  
  # check:
  #   runs-on: self-hosted
  #   steps:
  #   - name: Affichage Envvars
  #     uses: actions/checkout@v3

  logindocker:
    runs-on: self-hosted
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: buildx

  logingit:
    runs-on: self-hosted
    steps:
    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

  buildimage:
    runs-on: self-hosted
    needs: [logingit,logindocker]
    steps:
    - name: build image
      uses: actions/checkout@v3
    - run: docker build -t ${GITHUB_REPOSITORY}:build-temp .

# Utilisation variables entre les taches
# ordonnancement des taches
# Dépendances entre les taches
# à minia build + push sur ghcr.io l'image sitedocs
# besoin de : docker login + spécification du nom du registre + authentification
