name: 'build'

on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
#      - name: "Build:checkout"
#        uses: actions/checkout@v2
#      - name: 'Build:dockerimage'
#        uses: docker/build-push-action@v2
      - name: "build:pushimage"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          registry: ghcr.io
          username: "poseidon974"
          password: ${{ secrets.PAT }}
          repository: poseidon974/cours
          tags: latest