name: Deployement sitedocs
on: push
jobs:
  
  # check:
  #   runs-on: self-hosted
  #   steps:
  #   - name: Affichage Envvars
  #     uses: actions/checkout@v3
  #   - run: |
  #       set
  #       echo "tag name ${{ github.ref_name }}"

  # logindocker:
  #   runs-on: self-hosted
  #   steps:
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2
  #     id: buildx

  logingit:
    runs-on: self-hosted
    steps:
    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

  buildimage:
    runs-on: self-hosted
    needs: [logingit]
    steps:
    - name: build image
      uses: actions/checkout@v3
    - run: docker build -t ${GITHUB_REPOSITORY}:build-temp .

  pushimage:
    runs-on: self-hosted
    needs: [buildimage]
    steps:
    - name: Push image
      uses: actions/checkout@v3
    - run: |
        echo ${secrets.GITHUB_TOKEN} |  docker login ${GITHUB_REPOSITORY} -u ${github.actor} --password-stdin
        docker image tag ${GITHUB_REPOSITORY}:build-temp ${GITHUB_REPOSITORY}:${github.ref_name:-devel}
        docker image push  ${GITHUB_REPOSITORY}:${github.ref_name:-devel}
        docker logout
    - name: clean after
      uses: actions/checkout@v3
    - run: docker image rm ${GITHUB_REPOSITORY}:build-temp ${GITHUB_REPOSITORY}:${github.ref_name:-devel}


# Utilisation variables entre les taches
# ordonnancement des taches
# Dépendances entre les taches
# à minia build + push sur ghcr.io l'image sitedocs
# besoin de : docker login + spécification du nom du registre + authentification
