name: test-action-1
on: push
jobs:
    Env_vars:
  
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Print Env vars
      run: |
        set
    
    # - name: build image
    #   run: |
    #     ls -l
    #     pwd

    Login_git:
    runs-on: self-hosted
    steps:
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.access.token }}

# Utilisation variables entre les taches
# ordonnancement des taches
# Dépendances entre les taches
# à minia build + push sur ghcr.io l'image sitedocs
# besoin de : docker login + spécification du nom du registre + authentification